DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS menu_items CASCADE;
DROP TABLE IF EXISTS ordered_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS pending_order CASCADE;



 CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  admin BOOLEAN DEFAULT FALSE
);

 CREATE TABLE menu_items (
  id SERIAL PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  price INTEGER NOT NULL,
  ingredients TEXT,
  inventory BOOLEAN NOT NULL DEFAULT TRUE,
  food_photo_url VARCHAR(255) NOT NULL
);

 CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  order_started TIMESTAMP DEFAULT NOW(),
  order_fulfilled TIMESTAMP,
  order_status BOOLEAN,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

 CREATE TABLE ordered_items (
  id SERIAL PRIMARY KEY NOT NULL,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  menu_id INTEGER REFERENCES menu_items(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL
);

CREATE TABLE cart (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  menu_id INTEGER REFERENCES menu_items(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL,
  cart_date TIMESTAMP DEFAULT NOW(),
  active BOOLEAN
);


